### ISSUE TITLE
Ekleme - Swifthane ve Late Night Muhabbetleri

### ISSUE THREAD

**Issue by ahmetws** [celil/SwiftKaynaklari#19]
Selamlar,
Swifthane ve Late Night Muhabetleri'ni listeye eklersek cok guzel olur. Hangi kategorilere koyacagimi bulamadigimdan PR atmadim. Belki bir Podcast kategorisi acabiliriz. Ne dersiniz?

**Comment by celil** [comment]
Bence podcast için bir kategori açalım. Sen açıp PR mı atarsın yoksa ben mi açayım?

**Comment by ahmetws** [comment]
Ben eklemeyi yaptım.
