### ISSUE TITLE
Ekleme - GitHub Repo'ları

### ISSUE THREAD

**Issue by uy** [celil/SwiftKaynaklari#8]
Merhaba,

Swift & iOS için, ihtiyaç duyduğum bütün geliştirmeleri ileride lazım olur tuttuğum repo'm var. Repo olarak ekleme yapılıyor mu? Eğer yapılıyorsa PR ile eklemeyi gerçekleştireyim mi?

https://github.com/uy/iOS-Swift-Little-Tricks

**Comment by celil** [comment]
Selam,

Tabii ki, çok da güzel olur. Araçlar bölümünün altına "Muhtelif" ya da "Çeşitli" diye yeni bir alan açıp bu alana reponuzu ekleyebilirsiniz.

Teşekkürler.
